# This is a Fury configuration file. It contains significant
# whitespace and is not intended to be human-editable.
#
# To start using Fury with this project, install Fury and run,
#
#   fury layer init
#
# For more information, please visit https://propensive.com/fury/
#
layerRef	QmPKysAuTXeAWFrCqCKckducQmjFvU11nKS89qovk9RDSW
published	Some	url	fury://furore.dev/propensive/caesura
		version	1.1
		layerRef	QmV16D5cJWS1HNcXKBhgo2xP4FXrSBAAL8DYY7mawXZgoe
# vim: set noai ts=12 sw=12:
